class AllErrors(Exception):
    pass


class KnownError(AllErrors):
    pass
